name: 'tweet_results'
description: 'Will tweet all the results'
inputs:
  cypress:
    description: 'Cypress Result'
    required: true
  linter:
    description: 'Linter Result'
    required: true
  deploy:
    description: 'Deploy Result'
    required: true
  badge:
    description: 'Badge Result'
    required: true
  email:
    description: 'Email Result'
    required: true
  consumer_key:
    description: 'Consumer Key'
    required: true
  consumer_secret:
    description: 'Consumer Secret'
    required: true
  access_key:
    description: 'Access Key'
    required: true
  access_secret:
    description: 'Access Secret'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'